Still seeing:
FoundationDBClientTests > testInvalidGetVersionstamp() STANDARD_OUT
    2021-07-09 08:36:31.996 DEBUG [fdb-facade,2658cb66f10f4bd8,2658cb66f10f4bd8] 2063 --- [ault-executor-1] i.g.p.l.f.FoundationDbGrpcFacade         : Starting transaction unnamed_run_transaction against db: fdb
    2021-07-09 08:36:32.002 DEBUG [fdb-facade,2658cb66f10f4bd8,2658cb66f10f4bd8] 2063 --- [ault-executor-1] i.g.p.l.f.FoundationDbGrpcFacade         : GetVersionstampRequest
    2021-07-09 08:36:32.004 DEBUG [fdb-facade,2658cb66f10f4bd8,2658cb66f10f4bd8] 2063 --- [ault-executor-1] i.g.p.l.f.FoundationDbGrpcFacade         : CommitTransactionRequest
    2021-07-09 08:36:32.004 DEBUG [fdb-facade,2658cb66f10f4bd8,61d607dfa5e04a8f] 2063 --- [     fdb-java-1] i.g.p.l.f.FoundationDbGrpcFacade         : Committed transaction: -1
    2021-07-09 08:36:32.005  WARN [fdb-facade,2658cb66f10f4bd8,66550e436487c506] 2063 --- [     fdb-java-2] i.g.p.l.f.FoundationDbGrpcFacade         : failed to get versionstamp

    com.apple.foundationdb.FDBException: Transaction is read-only and therefore does not have a commit version
    	at com.apple.foundationdb.FutureKey.FutureKey_get(Native Method) ~[fdb-java-6.2.22.jar:na]
    	at com.apple.foundationdb.FutureKey.getIfDone_internal(FutureKey.java:33) ~[fdb-java-6.2.22.jar:na]
    	at com.apple.foundationdb.FutureKey.getIfDone_internal(FutureKey.java:25) ~[fdb-java-6.2.22.jar:na]
    	at com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:63) ~[fdb-java-6.2.22.jar:na]
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

    2021-07-09 08:36:32.010  WARN [fdb-facade,2658cb66f10f4bd8,2658cb66f10f4bd8] 2063 --- [ault-executor-2] i.g.p.l.f.FoundationDbGrpcFacade         : onError from client in executeTransaction

    io.grpc.StatusRuntimeException: CANCELLED: client cancelled
    	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.38.0.jar:1.38.0]
    	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:284) ~[grpc-stub-1.38.0.jar:1.38.0]
    	at brave.grpc.TracingServerInterceptor$TracingServerCallListener.onCancel(TracingServerInterceptor.java:168) ~[brave-instrumentation-grpc-5.13.2.jar:na]
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) ~[grpc-core-1.38.0.jar:1.38.0]
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) ~[grpc-core-1.38.0.jar:1.38.0]
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:844) ~[grpc-core-1.38.0.jar:1.38.0]
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.38.0.jar:1.38.0]
    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.38.0.jar:1.38.0]
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]